
runtime: python39

handlers:
- url: /$
  static_files: index.html
  upload: index\.html
  mime_type: text/html

- url: /(artifacts\.jar|content\.jar)
  static_files: \1
  upload: (artifacts\.jar|content\.jar)
  mime_type: application/octet-stream

- url: /web/(site\.css)
  static_files: web/\1
  upload: web/(site\.css)
  mime_type: text/\1

- url: /web/(site\.xsl)
  static_files: web/\1
  upload: web/(site\.xsl)
  mime_type: application/xml

- url: /site\.xml
  static_files: site.xml
  upload: site\.xml
  mime_type: application/xml

- url: /features/(.*\.jar)
  static_files: features/\1
  upload: features/.*\.jar
  mime_type: application/octet-stream

- url: /plugins/(.*\.jar)
  static_files: plugins/\1
  upload: plugins/.*\.jar
  mime_type: application/octet-stream
